pipeline {
    agent any

    environment {
        S3_BUCKET = 'my-s3-bucket-for-jenkins-pipeline-setup'
        S3_KEY = 'my-app.zip'
        ENVIRONMENT_NAME = 'Linux-based-web-application-env'
        APPLICATION_NAME = 'linux-based-web-application'
        AWS_REGION = 'us-east-1'
        SECRET_NAME = 'secret-jenkins-access'  // Replace with your actual secret name
    }

    stages {
        stage('Retrieve AWS Credentials from Secrets Manager') {
            steps {
                script {
                    // Retrieve the entire secret as plain text
                    def secretValue = sh(script: "aws secretsmanager get-secret-value --secret-id ${SECRET_NAME} --query 'SecretString' --output text --region ${AWS_REGION}", returnStdout: true).trim()
                    
                    // Split the secret into access key and secret key assuming it's stored as two lines or separated by space
                    def secretParts = secretValue.split('\n')
                    env.AWS_ACCESS_KEY_ID = secretParts[0].trim()
                    env.AWS_SECRET_ACCESS_KEY = secretParts[1].trim()
                }
            }
        }

        stage('Checkout') {
            steps {
                git url: 'https://github.com/ManojKamatam/Beanstalk_Deployments_maintainingVersions-SecretManager.git', branch: 'main'
            }
        }
        
        stage('Upload to S3') {
            steps {
                sh "aws s3 cp application.zip s3://${S3_BUCKET}/${S3_KEY} --region ${AWS_REGION}"
            }
        }

        stage('Create Application Version') {
            steps {
                sh """
                    aws elasticbeanstalk create-application-version \
                    --application-name ${APPLICATION_NAME} \
                    --version-label ${VERSION_LABEL} \
                    --source-bundle S3Bucket=${S3_BUCKET},S3Key=${S3_KEY} \
                    --region ${AWS_REGION}
                """
            }
        }

        stage('Update Elastic Beanstalk Environment') {
            steps {
                sh """
                    aws elasticbeanstalk update-environment \
                      --application-name ${APPLICATION_NAME} \
                      --environment-name ${ENVIRONMENT_NAME} \
                      --version-label ${VERSION_LABEL} \
                      --region ${AWS_REGION}
                """
            }
        }
    }

    post {
        always {
            echo 'Deployment process completed.'
        }
    }
}
